const abc = require('./logger')
const abcd = require('./util/helper')
const a = require('../validator/formatter')
abc.logging('rahul')
abc.welcome1()
console.log(abc.link1)
abcd.date()
abcd.month()
abcd.info()
a.trim1()
a.uppercase()
a.lowercase()
